locals {
  # Referencing variables inside a local
  full_app_name = "${var.app_name}-${var.app_env}"

  timestamp = timestamp()

  app_conf_content = <<-EOT
    # Auto-generated by Terraform - do not edit manually
    app_name    = ${local.full_app_name}
    environment = ${var.app_env}
    port        = ${var.app_port}
  EOT

  database_conf_header = <<-EOT
    # Auto-generated by Terraform - do not edit manually
    db_name = ${var.db_name}
    db_user = ${var.db_user}
    db_port = ${var.db_port}
  EOT
}
